env:
  RUBY_VERSION: 2.6
name: Rails tests
on: [push,pull_request]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Test
        run: |
          gem update --system
          gem install bundler
          gem install rubocop
          gem install rspec
          rubocop
          rspec
