env:
  RUBY_VERSION: 2.6
name: Rails tests
on: [push,pull_request]
jobs:
  bundler:
    name: Bundler
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Update gems
        run: gem update --system
      - name: Install bundler
        run: gem install bundle
  rubocop:
    name: Rubocop
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Install Rubocop
        run: gem install rubocop
      - name: Check code
        run: rubocop
  rspec:
    name: Rspec
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Run Specs
        run: gem install rspec
      - name: Check code
        run: bundle exec rake
